coinsapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.all_coindata, name='index'),
    url(r'^(?P<coins_id>[0-9]+)/$', views.build_chart, name='bokeh'),
    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

cryptoproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
# You should always use include() when you include other URL patterns.
# admin.site.urls is the only exception to this.
    url(r'^admin/', admin.site.urls),
# to add url patterns from coinsapp
# urls can changed dynamicaly within the app, and the app can be sued in several projects
# otherwise, we could add patterns here
    url(r'^', include('coinsapp.urls')),

]

coinsapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models

#basically, we are forming a database structure for our сsutom data here for our


class Coin(models.Model):
    coin_ticker = models.CharField(max_length=40)

    def __str__(self):
        return self.coin_ticker

class Value(models.Model):

    coin = models.ForeignKey('Coin', on_delete=models.CASCADE)
    coin_basevolume = models.FloatField(default=0)
    # ForeignKey, That tells Django each Value is related to a single Coin
    coin_value = models.FloatField(default=0)
    # FloatField is the same as DecimalField but different
    reqtime = models.DateTimeField(default=datetime.now, blank=True)
    sma = models.FloatField(default=0)


    def __str__(self):
        return u'value: %s time: %s volume: %s' % (self.coin_value, self.reqtime, self.coin_basevolume)


class Coinproperties(models.Model):
    coin = models.ForeignKey('Coin', on_delete=models.CASCADE)
    coin_perchange = models.FloatField(default=0)
    coin_change = models.FloatField(default=0)
    volume_change = models.FloatField(default=0)
    coin_changehalf = models.FloatField(default=0)
    volume_changehalf = models.FloatField(default=0)
    #volumechnage_time = models.FloatField(default=0)

class Gems(models.Model):
    gem_name = models.CharField(max_length=40)
    gemStartPrice = models.FloatField(default=0)
    gemDip = models.FloatField(default=0)
    gemReqtime = models.DateTimeField(default=datetime.now, blank=True)
    coinid =  models.IntegerField(default=0)

coinsapp/views.py
from django.shortcuts import render, render_to_response

from bokeh.plotting import figure, output_file, show
from bokeh.embed import components
from bokeh.resources import CDN
from models import Coin, Value, Coinproperties, Gems
from django.http import Http404
from datetime import datetime, timedelta
import numpy as np
from numpy import convolve

def all_coindata(request):

    coins_list = Coin.objects.order_by('-coinproperties__coin_changehalf')
    properties = Coinproperties.objects.all()
    gems = Gems.objects.all()
    # value_list_recent= value_list_recent["coin_value"]
    context = {'coins_list': coins_list, 'properties':properties, 'gems':gems}
    return render(request, 'coinsapp/index.html', context)

def build_chart(request, coins_id):

    try:
        c = Coin.objects.get(id=coins_id)
        x=[]
        y=[]
        sMa=[]
        nan = float('nan')
        for values in c.value_set.order_by('reqtime'):
            x.append(values.reqtime)
            y.append(values.coin_value)
            if values.sma == 0.0:
                sMa.append(nan)
            else:
                sMa.append(values.sma)
    # create a new plot with a title and axis labels


        def movingaverage (values, window):
            weights = np.repeat(1.0, window)/window
            sma = list(np.convolve(values, weights, 'valid'))

            n=0

            while (n < window-1):
                n=n+1
                nan = float('nan')
                sma.insert(0,nan)
            return sma

        coin_ticker=c.coin_ticker
        p = figure(title=c.coin_ticker, x_axis_label='Time', y_axis_label='Price', x_axis_type='datetime', height=250)

        sma_20 = movingaverage (y, 20)
        p.line( x,sma_20, legend="SMA 20", line_color="green", line_width=1 )

        sma_50 = movingaverage (y, 30)
        p.line( x,sma_50, legend="SMA 50", line_color="pink", line_width=1 )


        p.line( x,sMa, legend="SMA 10", line_color="red", line_width=2  )

        p.toolbar.logo = None
        # add a line renderer with legend and line thickness
        p.line(x, y, legend=c.coin_ticker, line_width=2)
        p.circle(x, y, fill_color="white", size=8)
        p.sizing_mode = 'scale_width'
        p.legend.location = "bottom_left"
        script, div = components(p, CDN)


        x_h=[]
        y_h=[]
        sMa_h=[]
        t=datetime.now()-timedelta(minutes=60)
        for values in c.value_set.filter(reqtime__gt=t).order_by('reqtime'):
            x_h.append(values.reqtime)
            y_h.append(values.coin_value)
            if values.sma == 0.0:
                sMa_h.append(nan)
            else:
                sMa_h.append(values.sma)

        #sma_ = movingaverage (y, 5)
        p_h = figure(title=c.coin_ticker, x_axis_label='Time', y_axis_label='Price', x_axis_type='datetime', height=250)
        p_h.toolbar.logo = None
        # add a line renderer with legend and line thickness
        p_h.line(x_h, y_h, legend=c.coin_ticker, line_color="green", line_width=2)
        p_h.line(x_h, sMa_h, legend="SMA 10",  line_color="red", line_width=1)
        p_h.circle(x_h, y_h, fill_color="white", size=8)
        p_h.sizing_mode = 'scale_width'
        p_h.legend.location = "bottom_left"
        script_h, div_h = components(p_h)
        # output_file("lines.html")
        # show(p)

        c = Coin.objects.get(id=coins_id)
        value = c.value_set.order_by('reqtime')
    except Value.DoesNotExist:
        raise Http404("Coin value does not exist")
    return render(request,'coinsapp/coin_chart.html',
        {'bk_script' : script , 'bk_div' : div, 'h_bk_script':script_h, 'h_bk_div':div_h, 'value':value, 'coin_ticker':coin_ticker} )

coinsapp/templates/coinsapp/coin_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
  {# Load the tag library #}
  {% load bootstrap4 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
     <meta charset="utf-8">
     <title>Bokeh Plot</title>

<link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css" type="text/css" />

<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
<script type="text/javascript">
 Bokeh.set_log_level("info");
</script>

<style>
          html {
            width: 90%;
            height: 100%;
          }
          body {
            width: 90%;
            height: 100%;
            margin: auto;
          }
        </style>

 </head>

<body>
    <div style="width:100%, align:center;">
    <h3>{{ coin_ticker }}</h3>
    {{ bk_script|safe }}
    {{ bk_div|safe }}

    <h3>One hour time frame</h3>
    {{ h_bk_script|safe }}
    {{ h_bk_div|safe }}
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg">

          <table class="table table-dark  table-bordered">
{% for key in value %}
<tr>
  <td>{{ key.reqtime|date:'d H:i' }}</td>
  <td>{{ key.coin_value }} $ </td>

</tr>
  {% endfor %}
          </table>
        </div>
      </div>
    </div>

{{endfor}}
</body>
</html>

coinsapp/templates/coinsapp/index.html
{% if  coins_list %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg">
          {% if  gems %}
          <table class="table  table-bordered">
          <div style="width:100%"> <h3 style="text-align:center; background-color: #212529; color:#99B77B; padding:5px; margin-bottom:0px ;">tasty DIPs</h3></div>


            <tr>
          <th scope="col">COIN Name</th>
          <th scope="col" >DIP %</th>
          <th scope="col">Start price</th>
            </tr>

            {% for records in gems %}

            <tr>

              <th> <a style="color:#99B77B;" href="/{{ records.coinid }}/">{{ records.gem_name }}</a> </th>
              <td>{{ records.gemDip }}%</td>
              <td>{{ records.gemStartPrice }}$</td>


            </tr>
              {% endfor %}
          </table>
          {% else %}
          <div style="width:100%"> <h3 style="text-align:center; background-color: #212529; color:#99B77B; padding:5px; margin-bottom:0px ;">Sorry, no DIPs now</h3></div>
          {% endif %}

<table class="table table-dark  table-bordered">
<div style="width:100%"> <h3 style="text-align:center; background-color: #212529; color:#99B77B; padding:5px; margin-bottom:0px ;">Coins data from Coinmarketcap</h3></div>
  <tr>
<th scope="col">COIN Name</th>
<th scope="col" >price $</th>
<th scope="col">price change 2 h</th>
<th scope="col">price change 10 min</th>
  </tr>

  {% for coins in coins_list %}

  <tr>

    <th> <a style="color:#99B77B;" href="/{{ coins.id }}/">{{ coins.coin_ticker }}</a> </th>

    <td> {{ coins.value_set.all.last.coin_value }} $</td>
    <td>{{ coins.coinproperties_set.all.last.coin_change }}%</td>
    <td>{{ coins.coinproperties_set.all.last.coin_changehalf }}%</td>


  </tr>
    {% endfor %}
</table>

{% else %}
    <p>No coins are available.</p>
{% endif %}
</div>
</div>
</div>